name: Dependency review

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  review:
    name: dependency-review
    runs-on: ubuntu-latest
    steps:
      # actions/dependency-review-action@v4 (5d475c7729d7b3a9d3bbfcb3c8b023f8dd184001)
      - uses: actions/dependency-review-action@5d475c7729d7b3a9d3bbfcb3c8b023f8dd184001
